[build]
  publish = "public"
  command = "hugo --minify"

[build.environment]
  # specify normal Hugo version; extended will be installed automatically
  HUGO_VERSION = "0.115.0"
  HUGO_ENV = "production"
